### ISSUE TITLE
Information about use / examples in README

### ISSUE THREAD

**Issue by lindell** [isonet/barcode#3]
First I want to say thanks for making JsBarcode available to use in more than the standard way :smile: 
But the information in the README is a bit sparse and some information about how to use the library should be added.

**Comment by isonet** [comment]
Wow, the actual creator :D

I hope this module might be useful for someone, I created it for a personal project and I though I might as well share it.

I definitely agree, I did just update it and should be better now.
There are still quite some bugs that need fixing, this project is still in alpha right now ;)

**Comment by lindell** [comment]
Nice :smile: 

Take your time with the project, but if you consider it stable in the future let me know. I'm thinking of linking this project and [react-barcode](https://github.com/kciter/react-barcode) from the JsBarcode Readme for people that need it and using angular / react.
